name: buildx

on:
  push:
    branches: main
    tags: 'v*'

jobs:
  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Change for main
      id: change_version
      run: if [ "${{ steps.get_version.outputs.VERSION }}" == "main" ]; then echo ::set-output name=VERSION::latest; else echo ::set-output name=VERSION::${{ steps.get_version.outputs.VERSION }} -t stable; fi
    - name: Set up qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      if: github.repository == 'iqtlabs/aisonobuoy' && github.event_name == 'push'

    - name: Build and push platforms
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        docker buildx build \
          --platform linux/arm \
          --push \
          -t iqtlabs/aisonobuoy-ais:${{ steps.change_version.outputs.VERSION }} PiBuoyV2/services/ais && \
        docker buildx build \
          --platform linux/arm \
          --push \
          -t iqtlabs/aisonobuoy-power:${{ steps.change_version.outputs.VERSION }} PiBuoyV2/services/power && \
        docker buildx build \
          --platform linux/arm \
          --push \
          -t iqtlabs/aisonobuoy-record:${{ steps.change_version.outputs.VERSION }} PiBuoyV2/services/record && \
        docker buildx build \
          --platform linux/arm \
          --push \
          -t iqtlabs/aisonobuoy-s3-upload:${{ steps.change_version.outputs.VERSION }} PiBuoyV2/services/s3-upload && \
        docker buildx build \
          --platform linux/arm \
          --push \
          -t iqtlabs/aisonobuoy-sense:${{ steps.change_version.outputs.VERSION }} PiBuoyV2/services/sense
      if: github.repository == 'iqtlabs/aisonobuoy' && github.event_name == 'push'
