name: python_test
on: [push, pull_request]
jobs:
  sleepypidtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
          sudo apt-get update && sudo apt-get install -f python3-dev && \
          pip3 install -r ./PiBuoy/sleepypid/requirements.txt && \
          ./PiBuoy/sleepypid/test_sleepypid.py
  pibuoy2py:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
          sudo apt-get update && sudo apt-get install python3-dev && \
              find PiBuoyV2 -type f -name \*requirements.txt -exec pip3 install -r {} \; && \
              pip3 install codecov pytest-cov pytest && \
              pylint -E $(find PiBuoyV2 -type f -name \*py) && \
              find PiBuoyV2 -type f -name \*py | xargs -n1 pytype && \
              pytest -v -vv --cov-report term-missing --cov=PiBuoyV2 -c .coveragerc && \
              coverage report && \
              coverage xml
